#!/bin/sh
while read -r a b _;do
    case "$a" in
        MemTotal:) total=$(( b / 1024 )) ;;
        MemAvailable:) avail=$(( b / 1024 )) ; break ;;
    esac
done < /proc/meminfo
printf '%d/%d\n' "$((total - avail))" "$total"
