#!/usr/bin/env bash

aria2awk() {
    awk '/^Total| 1\|\.\//{
    if ($0 ~ /^Total/) {
        size = $3
        psize = substr($3, 1, length($3) - 3) + 0
        if (size ~ /GiB/) {
            total += psize * 1024
        } else if (size ~ /KiB/) {
            total += psize / 1024
        } else {
            total += psize
        }
    } else if ($0 ~ / 1\|\.\//) {
        split($0, a, "/")
        torrent_name = a[2]
    } 

    if (size && torrent_name) {
        printf("%8s\t%s\n", size, torrent_name)
        size = ""
        psize = ""
        torrent_name = ""
    }
} END {
        if (total >= 1024) {
            total /= 1024
            printf("%.1fGiB total\n", total)
        } else {
            printf("%.1fMiB total\n", total)
        }
}'
}
aria2awk2awk() {
    awk -F\\t '
{
    size = $1
    torrent_name = $2
    psize = substr(size, 1, length(size) - 3) + 0
    if (size ~ /GiB/) {
        total += psize * 1024
    } else if (size ~ /KiB/) {
        total += psize / 1024
    } else {
        total += psize
    }
    if (size && torrent_name) {
        printf("%8s\t%s\n", size, torrent_name)
    }
} END {
    if (total >= 1024) {
        total /= 1024
        printf("%.1fGiB total\n", total)
    } else {
        printf("%.1fMiB total\n", total)
    }
}'
}

tmpfile=$(mktemp)
tmpfile2=$(mktemp)
set +o noclobber
end() { 
    set -o noclobber
    rm "$tmpfile" "$tmpfile2" &>/dev/null
}
trap end EXIT
aria2c -S ./*.torrent | aria2awk | sort -h > "$tmpfile"
while [ $# -gt 0 ];do
    case "$1" in
        head)
            shift
            [[ "$1" =~ ^[-\+]?[0-9]+$ ]] || exit 1
            head -n -1 "$tmpfile" | head -n "$1" | aria2awk2awk > "$tmpfile2"
            cp "$tmpfile2" "$tmpfile" &>/dev/null
        ;;
        tail)
            shift
            [[ "$1" =~ ^[-\+]?[0-9]+$ ]] || exit 1
            head -n -1 "$tmpfile" | tail -n "$1" | aria2awk2awk > "$tmpfile2"
            cp "$tmpfile2" "$tmpfile" &>/dev/null
        ;;
    esac
    shift
done

cat "$tmpfile"
